name = "secrets-test"
version = "1.0.0"

[deployment]
nodes = 1
permissions = ["https://auth.hashicorp.com","https://api.cloud.hashicorp.com"]

[build]
dir = "build"
entry = "secrets-test_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "secrets-test.wasm"
command = "npm run build:release"
